# Stage 1: Build Node.js / Vite
FROM node:20-alpine AS builder

WORKDIR /usr/src/app

# Definimos variables que pasaremos desde docker-compose
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

# Copiar dependencias primero para cacheo de capas
COPY package*.json ./
RUN npm ci

# Copiar código fuente
COPY . .

# Compilar la aplicación React para producción
RUN npm run build

# Stage 2: Serve Nginx
FROM nginx:alpine

# Copiar la configuración personalizada de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiar archivos compilados del builder a la ruta de Nginx
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

# Exponer el puerto
EXPOSE 80

# Iniciar servidor Nginx
CMD ["nginx", "-g", "daemon off;"]
